- hosts: all
  tasks:
    - name: create service template
      become: yes
      template:
        src: temp.service.j2
        dest: /etc/systemd/system/deployruby.service

    - name: copy artifact
      copy:
        src: web.rb
        dest: /home/vagrant/web.rb
        mode: '0777'

    - name: enable and start service
      become: yes
      systemd:
        name: deployruby
        enabled: yes
        state: restarted
