- hosts: all
  tasks:
    - name: create service template
      become: yes
      template:
        src: temp.service.j2
        dest: /etc/systemd/system/deployruby.service

    - name: enable and start service
      become: yes
      systemd:
        name: deployruby
        enabled: yes
        state: restarted
